package com.example.conwayying.query.data.entity;

import android.arch.persistence.room.Dao;
import android.arch.persistence.room.Insert;
import android.arch.persistence.room.Query;

import java.util.List;

/**
 * DAO for AcademicClass entities
 */
@Dao
public interface AcademicClassDao {

    // Returns the rowid of the row inserted (since AcademicClass has int autogenerated PK, the
    //   returned long will the the new class_id for the Academic Class
    @Insert
    Long insert(AcademicClass academicClass);

    @Query("SELECT * FROM Academic_Class WHERE class_id = :classId")
    AcademicClass getClass(int classId);

    @Query("SELECT * FROM Academic_Class")
    List<AcademicClass> getAllClasses();

}
